version: 2.1

jobs:
  build:
    macos:
      xcode: "12.4.0"
    steps:
      - checkout
      - run: pod install
      - run:
          name: Build and Test
          command: |
            xcodebuild clean test -workspace YourWorkspace.xcworkspace -scheme YourScheme -destination "platform=iOS Simulator,name=iPad (8th generation),OS=14.4"

workflows:
  build_and_test:
    jobs:
      - build
